version

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -14,7 +14,7 @@ jobs:
         env:
           VERSION: ${{ github.ref_name }}
         run: |
-          [[ ! ${VERSION//[[:blank:]]/} =~ ^v[[:digit:]]+\.[[:digit:]]\.[[:digit:]]$ ]] && echo "[ERR] wrong version number format $VERSION"
+          echo $VERSION | grep -P "^v\d+\.\d+\.\d+$"  || echo "::error::Unexpected version" && exit 1
       #- name: Check out code
       #  uses: actions/checkout@v3
       #- name: Install Python
